AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Monefy Web App EC2 instance template

Parameters:
  EC2InstanceName:
    Type: String
    Default: Monefy-Sanic-Web-App
  AppEC2InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  AppImageId:
    Type: String
    Default: ami-0a1ee2fb28fe05df3
  AppKeyName:
    Type: String
    Default: my-aws-key
  GitRepository:
    Type: String
    Default: https://github.com/parseltonguedev/monefy-web-app.git
  GitBranch:
    Type: String
    Default: dropbox_auth
    AllowedValues:
      - master
      - dropbox_auth
  AppVpcId:
    Type: String
    Default: vpc-0118939e6a04e2843

Resources:

  MonefyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: Sanic-EC2-Profile
      Roles:
        - sanic-ec2-role

  MonefyWebAppInstance:
    Type: AWS::EC2::Instance
    DependsOn:
      - MonefyInstanceProfile
      - AppSecurityGroup
    Properties:
      ImageId: !Ref AppImageId
      InstanceType: !Ref AppEC2InstanceType
      IamInstanceProfile: !Ref MonefyInstanceProfile
      KeyName: !Ref AppKeyName
      SecurityGroupIds:
        - Ref: AppSecurityGroup
      Tags:
        -
          Key: Name
          Value: !Ref EC2InstanceName
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            su - ec2-user
            cd /home/ec2-user
            yum update -y
            yum upgrade -y
            yum groupinstall "Development Tools" -y
            yum install openssl11 openssl11-devel libffi-devel bzip2-devel wget sqlite-devel git python3-pip epel-release nginx certbot python-certbot-nginx -y
            wget https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tgz
            tar -xf Python-3.10.4.tgz
            cd Python-3.10.4/
            ./configure --enable-optimizations --enable-loadable-sqlite-extensions
            make && make altinstall
            cd /home/ec2-user
            amazon-linux-extras enable epel
            yum clean metadata
            aws s3 cp s3://bohdan-dev-bucket/monefied.key /etc/nginx
            aws s3 cp s3://bohdan-dev-bucket/monefied_xyz.crt /etc/nginx
            aws s3 cp s3://bohdan-dev-bucket/nginx.conf /etc/nginx
            aws s3 cp s3://bohdan-dev-bucket/monefied.service /etc/systemd/system/
            su ec2-user -c "git clone ${GitRepository}"
            cd monefy-web-app/
            su ec2-user -c "git checkout ${GitBranch}"
            su ec2-user -c "mkdir logs"
            su ec2-user -c "python3.10 -m venv env"
            su ec2-user -c "source env/bin/activate"
            su ec2-user -c "pip install -r requirements.txt"
            systemctl daemon-reload
            systemctl start monefied
            systemctl enable monefied
            systemctl start nginx
            systemctl enable nginx
            certbot --nginx -d monefied.xyz --non-interactive --agree-tos -m jrzord2@gmail.com
            nginx -s reload
            systemctl restart nginx

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Monefy Web App instance
      VpcId: !Ref AppVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
