name: Monefy Web App auto CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read

env:
  DROPBOX_TOKEN       : "TEST"
  DROPBOX_PATH        : "TEST"
  DROPBOX_APP_SECRET  : "TEST"

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Export environment variables for tests
      run: |
        export DROPBOX_TOKEN=${{ env.DROPBOX_TOKEN }}
        export DROPBOX_PATH=${{ env.DROPBOX_PATH }}
        export DROPBOX_APP_SECRET=${{ env.DROPBOX_APP_SECRET }}
    - name: Lint with pylint
      run: |
        pylint run.py src/
#    - name: Test with pytest
#      run: |
#        pytest --cov . --cov-report xml:/home/runner/coverage.xml
#    - name: Upload coverage reports to Codecov with GitHub Action
#      uses: codecov/codecov-action@v2
#      with:
#        files: /home/runner/coverage.xml
